USE [C:\USERS\JORGE\DOCUMENTS\FACULTAD\SEM2022-1\TEMAS SELECTOS DE PROGRAMACIÓN I\PRACTICAS\PRACTICA3\PRACTICA3\DBPOLOSFT.MDF]
Go
CREATE TABLE Tabla_Polos (
ID int identity(1,1) primary key NOT NULL,
Constante_K int NOT NULL,
Polo_1 varchar(20) NOT NULL,
Polo_2 varchar(20) NOT NULL 
);
